car_sale/urls.py
from django.urls import path, include
from . import views


urlpatterns = [
    path('', views.home, name='home'),
    path("car-saler-form/", views.car_saler_form, name="car-saler-form"),
    path('success/', views.successform, name='success'),
    path('search/', views.search, name="search")

]

cars_for_sale_online/urls.py
from django.contrib import admin
from django.urls import path, include
from user_authentication.views import loginPage, registerPage, logoutUser
from car_buy.views import car_buyer, car_buyer_save
from car_sale.views import resale
urlpatterns = [
    path('sign-up/', registerPage, name="register"),
    path('login/', loginPage, name="login"),
    path('admin/', admin.site.urls),
    path('', include('car_sale.urls')),
    path('car-buyer-form/<int:id>', car_buyer, name="car-buyer-form"),
    path('car-buyer-savedata/<int:id>',
         car_buyer_save, name="car-buyer-savedata"),
    path('logout/', logoutUser, name="logout"),
    path('resale/<int:id>', resale, name="resale")

]

car_buy/models.py
from django.db import models
from django.core.validators import *


class CarBuyer(models.Model):

    buyer_name = models.CharField(max_length=20)
    buyer_mobile = models.CharField(max_length=10, validators=[
                                    MinLengthValidator(10), MaxLengthValidator(10)])
    email = models.EmailField(null=True)
    make = models.CharField(max_length=50, null=True)
    model = models.CharField(max_length=50, null=True)
    year = models.IntegerField(default=2022)
    condition = models.CharField(max_length=10, default='Good')
    asking_price = models.CharField(max_length=12, default=15000)

templates/available.html
<html>
<body>
    </div>
    
    <center>
      <h1>Car resale available!</h1> 
      
      <p><a href="{% url 'home' %}">home</a></p>
    </center>
    </div>
  </body>
</html>

templates/base.html
<html>
<head>
    <title>Car App</title>
    <style>
        to go underneath the header and footer */
        body{        
            padding-top: 60px;
            padding-bottom: 40px;
        }
        .fixed-header, .fixed-footer{
            width: 100%;
            position: auto;        
            background: #e6e6e6;
            padding: 10px 0;
            color: #daf1f1;
            margin-top: auto;
        }
        .container{
            width: 80%;
            margin: 0 auto; /* Center the DIV horizontally */
        }
        nav a{
            color: #030303;
            text-decoration: none;
            padding: 7px 25px;
            display: inline-block;
        }
    </style>
    
</head>  
{% block body %}
{% if user.is_authenticated %}
 
    Wellcome {{user.username}}!  
 
{% endif %}

    <div class="fixed-header">
        <div class="container">
            <nav>
                <a href="{% url 'home'%}">Home</a>
                <a href="{% url 'car-saler-form' %}" style="text-decoration: none;"> List Car</a>
                <a href="#">Products</a>
                <a href="#">Services</a>
                {% if user.is_authenticated %}
                <a href="{% url 'logout'%}">Logout</a>&nbsp;&nbsp;
                {% else %}
                <a href="{% url 'login'%}">Login</a>&nbsp;&nbsp;
                {% endif %}
                

            </nav>
        </div>
    </div>
    {% block content%}
    {% endblock %}
{% endblock %}
</html>

templates/car_buyer_form.html
{% extends 'base.html'%}
{% block content %}
<script>
    function validateForm() {
        let name = document.forms["buyerForm"]["buyer_name"].value;
        if (name == "") {
            alert("Name must be filled out");
            return false;
        }
        let mobile = document.forms["buyerForm"]["buyer_mobile"].value;
        if (mobile == "") {
            alert("mobile must be filled out");
            return false;
        }
        let email = document.forms["buyerForm"]["email"].value;
        if (email == "") {
            alert("email must be filled out");
            return false;
        }
    }
</script>
    <center>
    <h1>Car Buy Form</h1>
    <form method = 'POST' action="{% url 'car-buyer-savedata' id=data.id %}" name="buyerForm" onsubmit="return validateForm()">
        {% csrf_token %}
        <table>
            
                <tr><th><label for="id_buyer_name">Buyer name:</label></th><td><input type="text" name="buyer_name" ></td></tr>
                <tr><th><label for="id_buyer_mobile">Buyer mobile:</label></th><td><input type="text" name="buyer_mobile" ></td></tr>
                <tr><th><label for="id_buyer_mobile">email:</label></th><td><input type="text" name="email" ></td></tr>
                <tr><th><label for="id_make">Make:</label></th><td><input type="text" name="make" value="{{data.make}}" readonly></td></tr>
                <tr><th><label for="id_model">Model:</label></th><td><input type="text" name="model" value="{{data.model}}" readonly></td></tr>
                <tr><th><label for="id_year">Year:</label></th><td><input type="number" name="year" value="{{data.year}}" readonly></td></tr>
                <tr><th><label for="id_condition">Condition:</label></th><td><input type="text" name="condition" value="{{data.condition}}" readonly></td></tr>
                <tr><th><label for="id_asking_pricce">Asking pricce:</label></th><td><input type="text" name="asking_price" value="{{data.asking_price}}" readonly></td></tr>
                        
        </table>
        <br>
        <button type="submit" >Submit</button>

        &nbsp; <a href="{% url 'home' %}">home</a>

    </form>
</center>
{% endblock %}

templates/car_saler_form.html
{% extends 'base.html' %}

{% block content %}
    <center>
    <h1 >Car Saler Form</h1>
    <form method = 'POST', action="{% url 'car-saler-form' %}">
        {% csrf_token %}
        <table class = 'w-50 table table-light'>
            {% for field in upload_form %}
            <tr>
                <th>{{field.label}}</th>    
                <td>{{ field }}</td>
            </tr>
            {% endfor %}
        </table>
        <button type="submit">Submit</button>&nbsp; <p><a href="{% url 'home' %}">home</a></p>
    </form>
</center>
{% endblock %}

templates/email.html
            
        {% block body %}
            <table border='5px'>
                <thead>
                    <tr>
                        {% comment %} <th>id</th> {% endcomment %}
                        <th>saler name</th>
                        <th>saler mobile</th>   
                        <th>email</th>
                        <th>make</th>
                        <th>model</th>
                        <th>year</th>
                        <th>condition</th>
                        <th>Asking price</th>
                        
                        
                    </tr>
                </thead>
                <tbody>
                    
                    <tr>
                        {% comment %} <td>{{ client.id }}</td> {% endcomment %}
                        <td>{{ client.saler_name }}</td>
                        <td>{{ client.saler_mobile  }}</td>
                        <td>{{ client.email }}</td>
                        <td>{{ client.make }}</td>
                        <td>{{ client.model }}</td>
                        <td>{{ client.year }}</td>
                        <td>{{ client.condition }}</td>
                        <td>{{ client.asking_price }}</td>
                        
                    </tr>
                    
                </tbody>    
            </table>
        {% endblock %}

templates/home.html
{% if user.is_authenticated %}
 
    Wellcome {{user.username}}!  
 
{% endif %}
<html>
<head>
    <title>Car App</title>
    <style>
        
        .fixed-header, .fixed-footer{
            width: 100%;
            position: fixed;        
            background: #e6e6e6;
            padding: 10px 0;
            color: #daf1f1;
            margin-top: 10px;
        }
        .container{
            width: 80%;
            margin: 0 auto; /* Center the DIV horizontally */
        }
        nav a{
            color: #030303;
            text-decoration: none;
            padding: 7px 25px;
            display: inline-block;
        }
    </style>
    <script>
        
        function resetfun() {
            var search = document.getElementById('searchbox').value =""
        }

        function validateForm() {
            let search = document.forms["indexForm"]["txtsearch"].value;
            if (search == "") {
                alert("Enter your filter data in searchbox!");
                return false;
            }
        }
        
    </script>
</head>  
<body>
    
    <div class="fixed-header">
        <div class="container">
            <nav>
                <a href="{% url 'car-saler-form' %}" style="text-decoration: none;"> List Car</a>
                <a href="#">About</a>
                <a href="#">Products</a>
                <a href="#">Services</a>
                {% if user.is_authenticated %}
                <a href="{% url 'logout'%}">Logout</a>&nbsp;&nbsp;
                {% else %}
                <a href="{% url 'login'%}">Login</a>&nbsp;&nbsp;
                {% endif %}
                

            </nav>
        </div>
    </div>
    <br><br><br><br><br><br><br>
        <form method='GET' action="{% url 'search'%}" name="indexForm" onsubmit="return validateForm()">
            
            <input type="text" placeholder="Search car" name="txtsearch" id='searchbox' value="{{searchval}}">
            <input  type="submit"  value="search">
            <button type="reset" onclick="searchfun()"><a href="{% url 'home'%}" style="text-decoration:none;">Reset</a></button>
            <br><br>
            {% block body %}
            <table border='5px'>
                <thead>
                    <tr>
                        <th>id</th>
                        <th>saler name</th>
                        <th>saler mobile</th>   
                        <th>email</th>
                        <th>make</th>
                        <th>model</th>
                        <th>year</th>
                        <th>condition</th>
                        <th>Asking price</th>
                        {% if user.is_authenticated %}
                            <th>Buy</th>
                        {% endif %}
                    </tr>
                </thead>
                <tbody>
                    {% for client in users %}
                    <tr>
                        <td>{{ client.id }}</td>&nbsp;
                        <td>{{ client.saler_name }}</td>&nbsp;
                        <td>{{ client.saler_mobile  }}</td>&nbsp;
                        <td>{{ client.email }}</td>&nbsp;
                        <td>{{ client.make }}</td>&nbsp;
                        <td>{{ client.model }}</td>&nbsp;
                        <td>{{ client.year }}</td>&nbsp;
                        <td>{{ client.condition }}</td>&nbsp;
                        <td>{{ client.asking_price }}</td>&nbsp;
                        {% if user.is_authenticated %}
                            {% if client.is_sell%}
                                <td><label>Sold</label></td>
                                {% if user.username == 'make'%}
                                    <td><button><a href="{% url 'resale' client.id  %}">Available</a></button></td>
                                {% endif %}
                            {% else %}
                                <td><a href="car-buyer-form/{{client.id}}">Buy</a></td>
                            {% endif %}
                        {% endif %}
                    </tr>
                    {% endfor %}
                </tbody>    
            </table>
                {% if users.has_other_pages %}
                
                    {% if users.has_previous %}
                    <a href="?page={{ users.previous_page_number }}{% if request.GET.txtsearch %}&txtsearch={{ request.GET.txtsearch }}{% endif %}">&laquo;</a>
                    {% else %}
                
                    {% endif %}
                    {% for i in users.paginator.page_range %}
                        {% if users.number == i %}
                            <span>{{ i }}</span>
                        {% else %}
                            <a href="?page={{ i }}">{{ i }}</a>
                        {% endif %}
                    {% endfor %}
                    {% if users.has_next %}
                        <a href="?page={{ users.next_page_number }}{% if request.GET.txtsearch %}&txtsearch={{ request.GET.txtsearch }}{% endif %}">&raquo;</a>

                    {% endif %}
                    
                {% endif %}
                
            {% endblock %}
                
        </form>
        
</body>
</html>

templates/login.html
<body>
	<div>
		<div>
			<div>
				<div>


					<h3 id="form-title">LOGIN</h3>
				</div>
				<div>
					<form method="POST" action="">
						{% csrf_token %}
						<div>
							<label >Username</label>
							<input type="text" name="username" placeholder="Username..." class="form-control">
						</div>
						<br>
						<div>
								<label >Password</label>
								<input type="password" name="password" placeholder="Password..." class="form-control" >
						</div>
						<br>
						<div>
							<input class="btn login_btn" type="submit" value="Login">
						</div>
					</form>

				</div>

				{% for message in messages %}
					<p id="messages">{{message}}</p>
				{% endfor %}			
		
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Don't have an account? <a href="{% url 'register' %}" class="ml-2">Sign Up</a>&nbsp; &nbsp; <a href="{% url 'home' %}">Home</a>
					</div>
			
				</div>
			</div>
		</div>
	</div>
</body>

templates/not_found.html
<html>
<body>
    </div>
    
    <center>
      <h1>Not Found</h1> 
      
      <p><a href="{% url 'home' %}">home</a></p>
    </center>
    </div>
  </body>
</html>

templates/register.html
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">
					<h3 id="form-title">Sign Up</h3>
				</div>
				<div class="d-flex justify-content-center form_container">

					<form method="POST" action="">
						
						{% csrf_token %}
						<div>
							
							<label >Username</label>
							{{form.username}}
						</div>
						<br>
						<div >
							<label >Email</label>
							{{form.email}}
						</div>
						<br>
						<div>
							<label >Password</label>
							{{form.password1}}
						</div>
						<br>
						<div>
							<label >ConfirnPassword</label>
							{{form.password2}}
						</div>
						<br><br>
				   		<div>
				 			<input class="btn login_btn" type="submit" value="Register Account">
				   		</div>

					</form>
				</div>

				{{form.errors}}
				
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Already have an account? <a href="{% url 'login' %}" class="ml-2">Login</a>&nbsp; &nbsp; <a href="{% url 'home' %}">Home</a>
					</div>
				</div>
			</div>
		</div>
	</div>
	<script>
		
		var form_fields = document.getElementsByTagName('input')
		form_fields[1].placeholder='Username..';
		form_fields[2].placeholder='Email..';
		form_fields[3].placeholder='Enter password...';
		form_fields[4].placeholder='Re-enter Password...';


		for (var field in form_fields){	
			form_fields[field].className += ' form-control'
		}
	</script>
</body>

templates/regsuccess.html
<html>
<body>
    </div>
    
    <center>
      <h1>Thank You</h1> 
      <p>We received your buy request <br/> we'll be in touch shortly!</p>
      <p><a href="{% url 'home' %}">home</a></p>
    </center>
    </div>
  </body>
</html>

templates/success.html
<html>
<body>
    </div>
    
    <center>
      <h1>Thank You</h1> 
      <p>We received your saler request id {{upload_form}};<br/> we'll be in touch shortly!</p>
      <p><a href="{% url 'home' %}">home</a></p>
    </center>
    </div>
  </body>
</html>